sudo: required
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
node_js:
- stable
env:
  global:
  - GH_REF: github.com/gauntface/simple-push-demo.git
  - secure: Zb5y956NolfZUubPVIJsrafqT0/6c+0lTqAVX1Tcnutv1cpemEVj1PihTm2aPjyigoDGxTd6Zpav+pkOy0PvdssyqhaJ/r7ERxk3kg7GabAK97OKCn9QXvvTyilbB1473dPurcn3FJ3J+JxTnTD8A/gDfvP6FZV0FkLGeSOQ0xWwTVKgoxutoFB+QQrK0vgrKLeJdZDBoe+hxTMMZRxwfshs6H2a/AOUUWrPkHjB7qfOFgrWrUUg7nKi5UK16w6lEHLeAQ3FDCbCAVWvN973VTbKT+NrIdUFwCM/bwIgH6ORwBjkA6QuTBn09iEEt/VWKyKCZQyqn4+H7L2QwNt4dYR5RtTvaLKDtWOslac/vRIQ1FE5H5wtEbfDqr1bijDrScEcbBHITkZqkqKe9NZE0lGsCoXQL12gax/cS9AC0n5J6sRqSXp51gVm40BQ3TsiOiqOlc6N646yFFCptLREpEmZnQ5364jgGz653s3qSowTPeVrSmq10eKoIACmsjS50ZHBRDQUxx20uV0TZJa5yW9d7IKZtcU5xAbNu7aATZ5Uvg3VcGZlO3zUgSkPJzgBpJxpJhPGjQZ1bLe17MMFYULhs6K8Rg5S9DsNRY0qEm1OOGjRMqFznx/Kf1PoOTu/llnoomgZTNWrfH9rpmqx64ggRSeY18Jiek2sqg0ZXos=
install:
- npm install
script:
- npm run test
- "./project/publish-gh-pages.sh"
