sudo: required
dist: trusty
language: node_js
cache:
  directories:
  - node_modules
node_js:
- stable
env:
  global:
  - GH_REF: github.com/gauntface/simple-push-demo.git
install:
- npm install
script:
- npm run test
- "./project/publish-gh-pages.sh"
