application: poly-air
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /components/*
  static_dir: static/components

- url: /
  static_files: static/index.html
  upload: static/index\.html

- url: /push
  script: main.app

- url: /register_track
  script: main.app

- url: /clear_registrations
  script: main.app

- url: /get_registrations
  script: main.app

- url: /*
  static_dir: static/

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
