application: gauntface-polyair
version: v2014-12-02
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /components/*
  secure: always
  static_dir: static/components

- url: /
  static_files: static/index.html
  secure: always
  upload: static/index\.html

- url: /push
  secure: always
  script: main.app

- url: /register_track
  secure: always
  script: main.app

- url: /clear_registrations
  secure: always
  script: main.app

- url: /get_registrations
  secure: always
  script: main.app

- url: /*
  secure: always
  static_dir: static/

- url: .*
  secure: always
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
